server:
  port: 8079
rpc:
  serializer: hessian
  loadBalance: random
  registry: zookeeper

management:
  endpoints:
    #暴露所有端点信息
    enabled-by-default: true
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  security:
    enabled: false
  health:
    elasticsearch:
      enabled: false
  prometheus:
    metrics:
      export:
        enabled: true