server:
  port: 8081
rpc:
  port: 6666
  name: rpc
  registry: zookeeper
  serializer: hessian
  loadBalance: roundrobin

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n%xEx"
